inputs:
  host:
    required: true
  username:
    required: true
  ssh-private-key:
    required: true
  branch:
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      id: get-branch
      run: |
        if [[ -z "${{ github.ref_name }}" && -z "${{ inputs.branch }}" ]]; then
          exit 1
        fi
        BRANCH_NAME="${{ github.ref_name || inputs.branch }}"
        echo "Using branch: $BRANCH_NAME"
        echo "name=$BRANCH_NAME" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v2

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - shell: bash
      run: |
        scp -o StrictHostKeyChecking=no \
          ${{ github.action_path }}/deploy.sh \
          ${{ inputs.username }}@${{ inputs.host }}:/tmp/${{ github.repository }}-deploy.sh

    - uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.ssh-private-key }}
        script_stop: true
        script: |
          chmod +x /tmp/${{ github.repository }}-deploy.sh
          /tmp/${{ github.repository }}-deploy.sh ${{ github.repository }} ${{ steps.get-branch.outputs.name }}
          rm /tmp/${{ github.repository }}-deploy.sh
