inputs:
  branch-name:
    required: false
    default: 'main'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Upload deploy script
      shell: bash
      run: |
        scp -o StrictHostKeyChecking=no \
          ${{ github.action_path }}/deploy.sh \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/tmp/deploy.sh

    - name: Run deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          chmod +x /tmp/deploy.sh
          /tmp/deploy.sh ${{ github.repository }} ${{ inputs.branch-name }}
          rm /tmp/deploy.sh
