name: 'Rust Deploy Action'
description: 'Deploy a Rust application to a VPS'
inputs:
  host:
    description: 'VPS host'
    required: true
  username:
    description: 'VPS username'
    required: true
  ssh-private-key:
    description: 'SSH private key'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Upload deploy script
      run: |
        scp -o StrictHostKeyChecking=no \
          ${{ github.action_path }}/deploy.sh \
          ${{ inputs.username }}@${{ inputs.host }}:/tmp/deploy.sh

    - name: Run deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.ssh-private-key }}
        script_stop: true
        script: |
          chmod +x /tmp/deploy.sh
          /tmp/deploy.sh ${{ github.repository }}
          rm /tmp/deploy.sh
